### ISSUE TITLE
Billing page is blank?

### ISSUE THREAD

**Issue by danielcompton** [envkey/envkey-app#10]
<img width="1280" alt="screenshot of envkey 28-06-18 4-47-20 pm" src="https://user-images.githubusercontent.com/811954/42013759-ee7bba4c-7af2-11e8-84fc-b2c85eb8a575.png">

When clicking on the Billing section in the app, it doesn't seem to show anything. I don't see any other issues in the app, or on my system around network connectivity.

**Comment by danenania** [comment]
Hey @danielcompton, thanks for the report - looking into it.

**Comment by danenania** [comment]
This should now be fixed @danielcompton
