### ISSUE TITLE
local hooks for local servers and toggle cloud sync

### ISSUE THREAD

**Issue by PatrickJS** [envkey/envkey-app#11]
I want to restart or update my env in either node or my client js bundle and it would be great to get a local "webhook" from the envkey app connecting with my local server. I only need this b/c I also have a `DISABLE_TRACKING` env key and sometimes I want it on or off depending on what I'm doing.

With that said I also want to change these values locally without syncing so maybe a dev checkbox feature that doesn't sync with the team until I toggle it back on

**Comment by danenania** [comment]
Both webhooks (which can be pointed anywhere, including localhost) and the ability to manage local environments through EnvKey are coming soon in a 2.0 release. Also a CLI -- so you should be able to set that up easily once it's released!

**Comment by gdi2290** [comment]
nice

**Comment by danenania** [comment]
This is now live in EnvKey v2! 

https://github.com/envkey/envkey

More details:

https://docs-v2.envkey.com/docs/automation-overview

It's been awhile @PatrickJS, but is this close to what you were looking for?
