### ISSUE TITLE
Show sub-environments in main view

### ISSUE THREAD

**Issue by PatrickJS** [envkey/envkey-app#13]
The only way to see the sub-envs are to click on the icon so it's not clear that you have sub-envs. It would be great if we can see them on the sidebar nested or even sections under the variables view
```
[     app-name    ][ development ][     staging      ][   production   ]
[main envs]
// vars
[first-sub-env] 
// vars
[second-sub-env]
// vars
```

**Comment by danenania** [comment]
Agreed that making sub-environments more immediately visible would be good -- I'll think about the best way to do this from a design perspective.

The CLI that's in the works will also be helpful for this. It has output modes that look very similar to your example.

**Comment by danielcompton** [comment]
A short-term fix could be to change the Sub-Environment button colour when sub environments exist? This caught me out recently when I was trying to work out where a value was coming from.

**Comment by danenania** [comment]
In EnvKey v2, which has finally launched, sub-environments (now called branches) still aren't visible in the sidebar (made some progress on this but it needs more work), but environments now have a little number next to them indicating whether they have branches, and how many.

https://github.com/envkey/envkey

https://docs-v2.envkey.com/docs/branches-and-local-overrides
