### ISSUE TITLE
Audit of modifications

### ISSUE THREAD

**Issue by thomasLeclaire** [envkey/envkey-app#17]
Today, use the application on production is highly risky. Modifications can be done easily without really consider the impact, and without way to rollback. 

nice features will be to have 
- Full audit of modifications done: Add, modification, removal,.. who did it, and when
- Possibility to activate double validation for some changes
- possibility to rollback a modification in one click

**Comment by danenania** [comment]
Thanks @thomasEffilab - this is in the works!

**Comment by codeitcody** [comment]
Good to hear!

Production issues are often caused by changes to environmental variables over code changes. Having a history of the environment  variables to enable easy rollback would be very useful.

**Comment by ctrlaltdylan** [comment]
@danenania it's been a couple years - any progress on this?

**Comment by danenania** [comment]
@ctrlaltdylan Yes, it will be included in our V2--already working nicely in development :) - release target is now set for Aug 1st. 2020.

**Comment by zjwhitehead** [comment]
Excited to try this out @danenania. Let me know if you need testers!

**Comment by weber93** [comment]
Checking on this.

**Comment by afrase** [comment]
@danenania Any updates on this feature?
Thanks!

**Comment by danenania** [comment]
@afrase @weber93 v2 is still in the works--it will include full audit logs. Getting close... stay tuned.

**Comment by michaelbridge** [comment]
Great to hear this is being worked on; from my perspective, it is definitely the enhancement that would have the most significant impact on the product.

**Comment by danenania** [comment]
EnvKey v2 is finally live, and includes audit logs: https://github.com/envkey/envkey
