### ISSUE TITLE
[Feature request]: Nested/namespaced variables

### ISSUE THREAD

**Issue by nadeemja** [envkey/envkey-app#2]
Hi,

I'm trying out Envkey with Meteor, and I'm loving it so far.

However, it's a little difficult to work with variables that need to store settings in JSON-format. 

Would be cool if Envkey natively supported JSON format in a variable.

Regards,

Nadeem

**Comment by danenania** [comment]
Hey Nadeem, thanks for the feedback. I'm glad to hear that it's working well with Meteor! Can you give me an example of the type of settings you might be storing so I have a sense of that? 

While I can understand how this would be useful, one of EnvKey's goals is to keep the ui simple and not have too many flags/options. In this case, it seems like you could store your json as a string and then just do:

```
var jsonSettings = JSON.parse(process.env.JSON_SETTINGS);
```

This seems simple enough that I'm not sure it merits a flag in the ui.
