### ISSUE TITLE
Delete field content without confirmation or undo

### ISSUE THREAD

**Issue by SeriousM** [envkey/envkey-app#20]
Hi, the app does not ask you if you really want to delete a field's content or give you the opportunity to undo a mistake.

![image](https://user-images.githubusercontent.com/462013/48834036-07a8d480-ed7d-11e8-93fc-63f35c586e7f.png)

Since the delete is right next to edit it's quite dangerous to lose important (and nowhere else saved!!) values.

Please add a confirmation box asap, thanks.

**Comment by danenania** [comment]
Agreed--this will be fixed in the upcoming 2.0 in two ways: 1 - multiple changes can be staged before committing them as a transaction, and 2 - version control will allow for easy rollbacks.

**Comment by SeriousM** [comment]
Any eta on this? Delete without warning is a real bummer.

**Comment by danenania** [comment]
We'll add a confirmation in the short term for the next release.

In the meantime, try clicking right in the middle of the field to edit (instead of the pencil icon) to avoid misclicks.

**Comment by danenania** [comment]
Sorry @SeriousM for the delay on this--it's now live in 1.4.2
