### ISSUE TITLE
Editing field content does not save without `enter`

### ISSUE THREAD

**Issue by mps-bluecrew** [envkey/envkey-app#22]
When you edit a variable's value for an environment, if you click outside the field the value turns to bullets but apparently does not sync.  In order to force the sync, you must press 'enter' - otherwise you lose the data you've entered, and it does not propagate.  There is no warning before the data loss, no confirmation that you want to clear all changes.

Expected behavior: either save changes (probably with confirmation) or clear changes only after confirmation.

**Comment by danenania** [comment]
Hi, I agree a confirmation here is a good idea--we'll get  that in soon.

**Comment by danenania** [comment]
@mps-bluecrew 1.4.2 now includes a confirmation that should prevent this kind of data loss. 

It also seems there had been a regression that prevented a prompt from displaying on edit to remind the user that the enter key commits and escape cancels--this may have contributed to the issue as well. That's now fixed too.
