### ISSUE TITLE
Allow multiple changes to be committed at once

### ISSUE THREAD

**Issue by yaselc** [envkey/envkey-app#24]
In credentials that require more than one entry, e.g. User/Password, AccessKey/SecretKey, EnvKey can generate inconsistencies, because each change is synchronized automatically, if in the middle of the change between one credential and the other the values are fetched, then an invalid pair will be obtained.
Should be allowed to pause the synchronization while the entries are been edited or commit multiple changes at once

**Comment by danenania** [comment]
@yaselc The ability to stage multiple updates will be included in 2.0, which is in the works.

**Comment by danenania** [comment]
This is now included in EnvKey v2, which is finally live! https://github.com/envkey/envkey
