### ISSUE TITLE
Permanently stuck at decrypting config... page

### ISSUE THREAD

**Issue by xueyongg** [envkey/envkey-app#26]
![image](https://user-images.githubusercontent.com/11015221/55457905-f4a4eb80-561d-11e9-8ac7-a0f260dcf95d.png)
The expected is to show me the configurations for my applications.

Currently, it is stuck at the loading page. 

Have tried to log out and in again, to encounter the same issue again.

Version: 1.4.5

**Comment by danenania** [comment]
Hi, could you send the console logs to [support@envkey.com](mailto:support@envkey.com)? In the context menu, go to View > Open Developer Tools, then console, then right click and save as.

**Comment by dbsanfte** [comment]
I have sent a screenshot and logs also, experiencing this myself, as are many people at our org.

**Comment by danenania** [comment]
This should now be fixed as of 1.4.10--was caused by [redux-saga #1592](https://github.com/redux-saga/redux-saga/issues/1592 in redux-saga), leading to unpredictable silent failure in web-of-trust verification loop after 100+ iterations (i.e. lots of users and ENVKEYs generated).

**Comment by gadfly361** [comment]
@danenania I am using version 1.4.10 and still hitting this bug. (Mac os version: 10.14.4)

**Comment by danenania** [comment]
@gadfly361 Could you email support@envkey.com? We need your account email so we can look at the session logs. Thanks!

**Comment by danenania** [comment]
@gadfly361 Investigating this now.

**Comment by danenania** [comment]
@gadfly361 This is likely caused by something else--could you send your console logs to support@envkey.com? In the context menu, go to View > Open Developer Tools, then console, then right click and save as. Thanks!
