### ISSUE TITLE
Ability to clone a sub-environment

### ISSUE THREAD

**Issue by tksumanth1994** [envkey/envkey-app#28]
Right now, export/import solves the problem, but that process is very time taking. If instead, you can add a clone option for the sub-environment, that would be very helpful 🙏

**Comment by danenania** [comment]
Thanks for the feedback! We’ll look into this—should be a quick addition.

**Comment by tksumanth1994** [comment]
@danenania still going through this time taking process.. did you guys happen to figure out anything about this?

**Comment by danenania** [comment]
@tksumanth1994 Sorry, this fell through the cracks, but we'll get it included in the next release along with the scroll fix today/tomorrow.

**Comment by danenania** [comment]
This is now live in 1.4.13
