### ISSUE TITLE
getting invalid passphrase when it works for my teammates

### ISSUE THREAD

**Issue by blai00** [envkey/envkey-app#31]
It keeps reporting that I am using an invalid passphrase that I am copying and pasting from 1pass. However, my coworker says that it works fine for him and the rest of the team. Is there something wrong with my account?

**Comment by danenania** [comment]
Hi! Passphrases are unique to each user so you wouldn't necessarily have the same passphrase as the rest of your team (unless you had set it up that way).

Can you try clicking the 'Forgot passphrase?' link below the passphrase input--that will guide you towards getting re-invited at which point you can set a new passphrase.

If you're still having problems after that please email support@envkey.com and we'll take a look at your account.

**Comment by blai00** [comment]
So if I don't use the app for a few days, the application will prompt that I re-login. Upon doing so, it asks for the master passphrase. Once I enter what I think is the team's master passphrase and receive an invalid code response, I then hit the "Forgot passphrase?" as suggested. I then hit cancel and it will ask that I re-login one more time and now it works and I skip the part about entering the passphrase. Not sure if that is how it is intended to work and maybe you can shed some light on this.

**Comment by danenania** [comment]
@blai00 Could you email support@envkey.com from your EnvKey account email address and we'll take a look? Thanks!
