### ISSUE TITLE
Ability to create app through CLI

### ISSUE THREAD

**Issue by conghoang** [envkey/envkey-app#32]
I want to have the ability to create envkey through CLI, because I am implementing a bootstrap process to init a project for my team.

**Comment by danenania** [comment]
Hi @congohoang, this is in the works as part of a big v2 release!

**Comment by conghoang** [comment]
When will we have v2?

**Comment by danenania** [comment]
EnvKey v2 is finally live, and it includes a full-featured CLI:  https://github.com/envkey/envkey
