### ISSUE TITLE
Adding a sub-environment creates a duplicate

### ISSUE THREAD

**Issue by klmall950** [envkey/envkey-app#4]
When adding a sub-environment, it is creating a duplicate.

![image](https://user-images.githubusercontent.com/2530349/32220728-3489f79e-be09-11e7-80e6-ce7d1c9961a1.png)

**Comment by danenania** [comment]
Hi, thanks for the bug report. This seems to be occurring when the base environment is empty. Working on a fix.

**Comment by danenania** [comment]
This should be fixed in v1.1.1

**Comment by klmall950** [comment]
Works great, thanks!
