### ISSUE TITLE
Allow for global variables across multiple apps

### ISSUE THREAD

**Issue by jon-j-warren** [envkey/envkey-app#41]
Something I haven't seen that would be a cool nice-to-have is global variables. A few of our apps have a lot of the same variables between them, and when we have to change the value of one, we end up having to go through all of the apps' configs to change all of the values individually. Something like "inherits from global" as a value option as well as a place to load in your global env variables that are available to all apps.

**Comment by danenania** [comment]
Hi! This is in the works for our v2 release—there’s no hard release date yet but we’re in track for q1 2020.
