### ISSUE TITLE
Upgrade to 1.4.16

### ISSUE THREAD

**Issue by mikeshultz** [envkey/envkey-app#45]
A recent automated upgrade appears to have turned my AppImage executable into an HTML document(a GitHub 404 page).  Looks like it's probably a bad release URL, which is also linked to on the envkey.com home page.

Good: https://github.com/envkey/envkey-app/releases/download/linux-x64-prod-v1.4.16/EnvKey-1.4.16.AppImage
Bad: https://github.com/envkey/envkey-app/releases/download/linux-x64-prod-v1.4.16/EnvKey-1.4.16-x86_64.AppImage

Hope that helps

**Comment by danenania** [comment]
Thanks for reporting this Mike! Fixing now.
