### ISSUE TITLE
Self-host ENVKEY server

### ISSUE THREAD

**Issue by priom** [envkey/envkey-app#46]
I love this project and it's really intuitive to use. My only concern is the security, this is definitely something which needs to be self-hosted so, wondering if there's a self-hosted solution or at least it's in the roadmap?

**Comment by danenania** [comment]
Yes @priom we're working on this! It will be part of a big v2 release which should be ready to go in q2 this year. Stay tuned :)

**Comment by priom** [comment]
Awesome @danenania, will keep my eyes open for it!

**Comment by danenania** [comment]
EnvKey v2 is finally live, and now includes self-hosting! https://github.com/envkey/envkey
