### ISSUE TITLE
Improve table usability

### ISSUE THREAD

**Issue by manuelmeurer** [envkey/envkey-app#47]
In the EnvKey macOS app, it's sometimes hard to not get lost since the table has a completely white background.
A "striped" table or at least highlighting the row that the cursor hovers over would help a lot! :)

**Comment by danenania** [comment]
Hi @manuelmeurer, the cell you're hovering over should be highlighted in bright blue--are you not seeing that?

**Comment by manuelmeurer** [comment]
Yeah, the cell is highlighted, but IMO it would make sense if the whole row was highlighted, so that when I hover over a cell in the rightmost column, I can quickly see the name of the variable in the leftmost column.
