### ISSUE TITLE
UI Zoom level of the desktop app is broken in 1.4.16

### ISSUE THREAD

**Issue by drcongo** [envkey/envkey-app#48]
My eyesight isn't great, and the low text contrast in EnvKey combined with my high DPI screen means I have to have the UI zoomed in about 3 levels. EnvKey has always forgotten my zoom settings between app restarts, but it would also always remember as soon as I hit either of the zoom keyboard shortcuts. The latest version doesn't remember though, and Cmd+Plus to zoom in no longer works. So I have to go to the menu and select View-> Zoom In three times. Weirdly though, EnvKey will spend the rest of the time I have it open occasionally reverting to standard zoom level, then back to what I set it at, and sometimes to a much more zoomed in state - presumably when it remembers my zoom preferences and then applies the three View->Zooms I did on top of that.

I'm on EnvKey 1.4.16, macOS 10.14.6

**Comment by danenania** [comment]
@drcongo Thanks for reporting--appears the shortcut issue is a [bug in electron](https://github.com/electron/electron/issues/15496). Strangely, the shortcut changed to `SHIFT`+`CMD`+`+` (note the SHIFT), but the shortcut in the menu wasn't updated. Will see what can be done on that, and will also look into the zoom level reverting/persisting zoom across sessions.

**Comment by drcongo** [comment]
Thanks @danenania, it does indeed work with the shift. Weirdly the zoom out is still without the shift.
This is enough to get me by for now though, so thanks!
