### ISSUE TITLE
Envkey downloads _way_ to much data from github.

### ISSUE THREAD

**Issue by nullstyle** [envkey/envkey-app#5]
<img width="683" alt="little_snitch_network_monitor" src="https://user-images.githubusercontent.com/366/32568191-25400f8c-c483-11e7-9a73-94700a4c822a.png">

I don't even really use the app... why has it downloaded this much data just from running in the background doing nothing?

**Comment by danenania** [comment]
That's just from requests to github.com or the total downloaded from anywhere? 

The requests to github come from the auto-update logic, which polls an updates.json file (https://raw.githubusercontent.com/envkey/envkey-app/master/envkey-electron/updates.json) every 10 minutes to see if an update is available. If one is available, it's downloaded in the background. So the data usage is a combination of the update downloads and all the updates.json checks adding up over time.

**Comment by nullstyle** [comment]
That's just from github-production-release-asset-2e65be.s3.amazonaws.com.  

> So the data usage is a combination of the update downloads and all the updates.json checks adding up over time.

My back of napkin math on how much data I've downloaded versus the number of releases you've made seems to indicate you've got a bug in your update logic.  Even if I had the app running in the background for every release you've put out (which isn't the case... I've restarted in the last 2 days), I'd expect something around `(45 releases x 50 MB/release) = 2250 MB` of downloaded data.

**Comment by danenania** [comment]
Yeah, that does sound high in that case. I'll take a look. Thanks for the bug report.

**Comment by danenania** [comment]
@nullstyle What platform are you on btw?

**Comment by nullstyle** [comment]
@danenania OS X Sierra

**Comment by danenania** [comment]
This should be fixed in v1.1.3

Thanks again for for discovering this @nullstyle.
