### ISSUE TITLE
Missing environment variable with inheritance chain

### ISSUE THREAD

**Issue by rvillanueva** [envkey/envkey-app#53]
### Problem
Several of our environment variables in development inherit from staging, which in turn inherits from production.

![image](https://user-images.githubusercontent.com/4154520/89428689-ad93a280-d70a-11ea-9150-574d36106916.png)

Intermittently, these key value pairs will disappear when we use `envkey_loader` to load variables. It seems to be only those that are doing chained inheritance, though it's hard to isolate the cause since it seems to happen even though we haven't changed anything.

### Workaround

Right now we can go in and just set the environment to `inherits production` instead of `inherits staging`, and if I recall correctly it's possible that just re-encrypting and re-sending `inherits staging` fixes the issue as well.

### Possible Causes
Best guess is that if a user updates a development key but doesn't have access to production, maybe the values don't inherit correctly?

**Comment by danenania** [comment]
Thanks for the bug report @rvillanueva! Looking into this...
