### ISSUE TITLE
Local Development Keys for SubEnvironments

### ISSUE THREAD

**Issue by klmall950** [envkey/envkey-app#6]
Not sure if this is a bug or intentional, but I wanted to access a sub-environment with my local dev key. Don't see a way to generate one though. We're working around this with Development Keys for now but ideally would prefer that each dev has the ability to use their own keys.

**Comment by danenania** [comment]
This is in the works. It requires a bit of a different treatment than the existing sub-environments implementation in order to allow per-user local overrides. Hoping to ship it in the next few days.

**Comment by pmdarrow** [comment]
@danenania does this feature exist now?

**Comment by danenania** [comment]
@pmdarrow not yet unfortunately. Some other things ended up taking priority, but it's on the short-list.

**Comment by danenania** [comment]
This is now included in EnvKey v2, which is finally live: https://github.com/envkey/envkey

Sub-environments are now called 'branches'. More info here: https://docs-v2.envkey.com/docs/branches-and-local-overrides
