### ISSUE TITLE
envkey.com down

### ISSUE THREAD

**Issue by thomasLeclaire** [envkey/envkey-app#60]
Major issue there: the full site is down.
can't access or modify any secrets.

**Comment by thomasLeclaire** [comment]
![image](https://user-images.githubusercontent.com/43581346/109673250-20b4a880-7b76-11eb-9fec-234041b2ec17.png)

**Comment by thomasLeclaire** [comment]
as seen together, related to a dns propagation issue. 
currently ok with google dns 8.8.8.8 as workaround

**Comment by danenania** [comment]
This is a DNS resolution issue with our DNS provider. Status here: https://dnsimple.statuspage.io/incidents/bcnzxs0mgz21?u=vwjqdflkmrpv

I'm glad to hear it's working with google DNS! We are looking in to registering a backup domain with another provider to add redundancy at this layer.

**Comment by danenania** [comment]
Should now be back to normal.
