### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by skoofer** [envkey/envkey-app#69]
Hi,

As admins of an organization in envkey, we have been experiencing performance of the start-up of the envkey app declining over time as we add more projects into the organization.

We now have ~235 projects in envkey. As org admins, we have access to all projects by default. However, it takes at least 2 minutes at best for the app to be fully loaded & in a usable state when our system is in a relatively idle state. When we are running other CPU-intensive processes (e.g. IDEs, collaboration tools) or run in battery-save mode whilst we start the envkey app, it takes a lot more and in some cases it even goes into a loop and won't start. Since we are planning to add more projects, we think it is only going to get worse.

The fact that it gets worse when more projects are added, tells me that the app may be doing (over-)eager fetching of resources of all the projects one has access to at the time of start-up —in an org admin's case it means all the projects. In our use cases, when we start the envkey app, we are only interested in a handful of projects. We don't need the resources of all the projects to be ready & loaded when the app starts.

Is there any room for improvement here? Any chance to move towards a more lazy-loading kind of approach maybe?

I am currently using v1.4.19 for Windows.

**Comment by danenania** [comment]
Hi Serkan,

Thanks for the comment. This is a priority for our v2 release, which is now fully functional and will be ready for beta in a matter of weeks. It is built to load apps on-demand and also uses a much faster approach to encryption, so it performs drastically better with a large number of apps. We're also working on a data importer to simplify migration from the v1.

**Comment by skoofer** [comment]
@danenania is there any news on the v2? It keeps getting worse as we add new projects over time.

**Comment by danenania** [comment]
@skoofer It's very close. We're doing final testing (including performance testing) and working on the v1 > v2 importer.

**Comment by skoofer** [comment]
@danenania any ETA on v2?

**Comment by chookie** [comment]
@danenania this is really a big issue for us now.  An update would be appreciated.
