### ISSUE TITLE
EnvKey can't connect to the internet.

### ISSUE THREAD

**Issue by geart891** [envkey/envkey-app#71]
Issue:
EnvKey app does not log me in. Instead it stuck in this screen. The internet is working fine. No firewall settings, I was sure that nothing blocking it from accessing internet.

![image](https://user-images.githubusercontent.com/27849964/123804378-5ea0be00-d917-11eb-8f1f-5d9f8c5ee281.png)

Comp specs:
Os bigsur 11.4
macbook m1
Go 1.16.5
node 16
EnvKey version (latest darwin version in this repo & download from the official website)

**Comment by danenania** [comment]
Hi Daniel. Sorry about that! Are you able to make requests to http://www.msftconnecttest.com/connecttest.txt (this is what the app uses for internet checks).

If that is working, could you open up the console (View > Toggle Developer Tools) right click in the console, and click Save As, then send the output to support@envkey.com

**Comment by danenania** [comment]
Hi @geart891, is this still an issue for you? Happy to re-open and get to the bottom of it if so.

**Comment by geart891** [comment]
Hey @danenania , thanks for replying. I have checked the link above and confirmed that my internet is not able to make any request to msftconnecttest. This is very strange because I can connect to other website normally. Is it possible to switch to a more reliable mechanism?
