### ISSUE TITLE
Adding new variable with existing name overwrites eixsting values

### ISSUE THREAD

**Issue by SeriousM** [envkey/envkey-app#75]
This is critical. The user should be asked to override existing values.

This happened to me as I was copy a key with almost same values but forgot to change the name.
And shwoops, all production values were gone (thankfully I had backups)

![envkey-issue](https://user-images.githubusercontent.com/462013/132361333-bdd2bba0-e8df-41ef-93ae-1323bb1c6ecb.gif)

**Comment by danenania** [comment]
Hi @SeriousM,  we'll add a warning for this scenario shortly!

**Comment by danenania** [comment]
Fixed in EnvKey v2: https://github.com/envkey/envkey
