### ISSUE TITLE
Desktop App not working at all after todays update

### ISSUE THREAD

**Issue by RDP07** [envkey/envkey-app#94]
I am using the v1 EnvKey desktop app and the app gave me a prompt today that said there is a new update available and plz restart... so i clicked the button... now my envkey doenst work anymore due to a JS error `Cannot find module 'electro-is-dev'`

I tried to delete envkey all together and re-downloaded v1 from this link: https://v1.envkey.com/, with no luck at all and I still am seeing the same error. Please help and let me know if there is anything you need from me or that I can do!

<img width="290" alt="Screen Shot 2022-04-28 at 1 00 39 PM" src="https://user-images.githubusercontent.com/22618689/165818292-985891d8-fb60-4521-889b-c4ea4c7b4110.png">

**Comment by danenania** [comment]
Fixed in v1.4.26

**Comment by RDP07** [comment]
Yess thank you so much, things seem to be working again!
